CAMERA_ANGLE = 51
FRAME_WIDTH = 480
DRONE_ROTATION_THRESHOLD = 20
FRONT_ROTATION_THRESHOLD = 20
DISTANCE_THRESHOLD = 50
ARUKO_QUEUE_SIZE = 5

SWITCH_ARUKO_HEIGHT_MAX = 40
SWITCH_ARUKO_HEIGHT_MIN = 20

ARUKO_BIG_ID = 610
ARUKO_BIG_WIDTH = 15.3

ARUKO_SMALL_ID = 99
ARUKO_SMALL_WIDTH = 3.8
